# [START appengine_websockets_yaml]
runtime: nodejs
env: flex

# [START scaling]
manual_scaling:
    instances: 1
# [END scaling]

# [START network]
network:
    session_affinity: true
# [END network]

# [END appengine_websockets_yaml]
