export const INTERNAL_NOTIFICATIONS_ADD = "INTERNAL_NOTIFICATIONS_ADD";
export const INTERNAL_NOTIFICATIONS_REMOVE = "INTERNAL_NOTIFICATIONS_REMOVE";

export const AUTH_INITIATE = "AUTH_INITIATE";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_UPDATE_CREDENTIALS = "AUTH_UPDATE_CREDENTIALS";
export const AUTH_CLEAR_CREDENTIALS = "AUTH_CLEAR_CREDENTIALS";
export const AUTH_REDIRECT = "AUTH_REDIRECT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";

export const USER_INIT = "USER_INIT";
export const USER_END = "USER_END";
export const USER_ERROR = "USER_ERROR";
export const USER_FETCH_DATA = "USER_FETCH_DATA";
export const USER_FETCH_HISTORY = "USER_FETCH_HISTORY";

export const FRIENDS_FETCH_REQUESTS = "FRIENDS_FETCH_REQUESTS";
export const FRIENDS_ADD = "FRIENDS_ADD";
export const FRIENDS_DENY_REQUEST = "FRIENDS_DENY_REQUEST";
export const FRIENDS_CONFIRM_REQUEST = "FRIENDS_CONFIRM_REQUEST";

export const ROOM_ALL = "ROOM_ALL";
export const ROOM_CREATE = "ROOM_CREATE";
export const ROOM_ADD = "ROOM_ADD";
export const ROOM_JOIN = "ROOM_JOIN";
export const ROOM_LEAVE = "ROOM_LEAVE";
export const ROOM_ERROR = "ROOM_ERROR";
export const ROOM_DATA = "ROOM_DATA";
export const ROOM_MESSAGE_ADD = "ROOM_MESSAGE_ADD";
export const ROOM_METADATA_ADD = "ROOM_METADATA_ADD";
export const ROOM_METADATA_CHANGE = "ROOM_METADATA_CHANGE";
export const ROOM_USER_CHANGED = "ROOM_USER_CHANGED";
export const ROOM_USER_ENTERED = "ROOM_USER_ENTERED";
export const ROOM_USER_LEFT = "ROOM_USER_LEFT";
export const ROOM_INIT = "ROOM_INIT";
export const ROOM_END = "ROOM_END";
