export const ROOM_TYPE_LEARN = "learn";
export const ROOM_TYPE_PRACTICE = "practice";
export const ROOM_TYPE_COMPETE = "compete";
export const ROOM_TYPE_POLUTION = "ROOM_POLUTION";
export const ROOM_TYPE_PLACES = "ROOM_PLACES";

export const MAP_ZOOM_LEVEL = 4;
export const MAP_LAYER =
	"https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png";

export const ALGORITHM_BREADTH = "ALGORITHM_BREADTH";
export const ALGORITHM_DEPTH = "ALGORITHM_DEPTH";
export const ALGORITHM_BREADTH_OBSERVABLE = "ALGORITHM_BREADTH_OBSERVABLE";
export const ALGORITHM_DEPTH_OBSERVABLE = "ALGORITHM_DEPTH_OBSERVABLE";

export const GRAPH_LEARN_GRAPHS = "GRAPH_LEARN_GRAPHS";
export const GRAPH_LEARN_REPRESENTATIONS = "GRAPH_LEARN_REPRESENTATIONS";
export const GRAPH_LEARN_TRAVERSALS = "GRAPH_LEARN_TRAVERSALS";

export const COMPETE_BREADTH = "ALGORITHM_BREADTH";
export const COMPETE_DEPTH = "ALGORITHM_DEPTH";

export const GRAPH_MANAGED_REMOVE_NODE = "GRAPH_MANAGED_REMOVE_NODE";
export const GRAPH_MANAGED_ADD_EDGE = "GRAPH_MANAGED_ADD_EDGE";
export const GRAPH_MANAGED_REMOVE_EDGE = "GRAPH_MANAGED_REMOVE_EDGE";
export const GRAPH_MANAGED_ALGORITHM = "GRAPH_MANAGED_ALGORITHM";
export const GRAPH_MANAGED_COMPETE = "GRAPH_MANAGED_COMPETE";
